export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS'
export const FETCH_CATAGORIES = 'FETCH_CATAGORIES'
export const FETCH_PRODUCTS_BY_ID = 'FETCH_PRODUCTS_BY_ID'